// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Data;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260514095818_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("server.Models.Appointment", b =>
                {
                    b.Property<string>("appointment_id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly?>("appointment_date")
                        .HasColumnType("date");

                    b.Property<string>("arrival_status")
                        .HasColumnType("longtext");

                    b.Property<string>("assigned_advisor_name")
                        .HasColumnType("longtext");

                    b.Property<string>("assignee_contact")
                        .HasColumnType("longtext");

                    b.Property<string>("assignee_first_name")
                        .HasColumnType("longtext");

                    b.Property<string>("assignee_last_name")
                        .HasColumnType("longtext");

                    b.Property<string>("client_phone")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("created_by")
                        .HasColumnType("longtext");

                    b.Property<string>("cs_no")
                        .HasColumnType("longtext");

                    b.Property<string>("first_name")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("last_modified_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("last_modified_by")
                        .HasColumnType("longtext");

                    b.Property<string>("last_name")
                        .HasColumnType("longtext");

                    b.Property<string>("n1d_confirmation")
                        .HasColumnType("longtext");

                    b.Property<string>("n1h_confirmation")
                        .HasColumnType("longtext");

                    b.Property<string>("olb_no")
                        .HasColumnType("longtext");

                    b.Property<string>("plate_number")
                        .HasColumnType("longtext");

                    b.Property<string>("remarks")
                        .HasColumnType("longtext");

                    b.Property<string>("reschedule_id")
                        .HasColumnType("longtext");

                    b.Property<TimeOnly?>("scheduled_arrival_time")
                        .HasColumnType("time(6)");

                    b.Property<string>("service_category")
                        .HasColumnType("longtext");

                    b.Property<string>("source")
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .HasColumnType("longtext");

                    b.Property<string>("status_remarks")
                        .HasColumnType("longtext");

                    b.Property<string>("vehicle_model")
                        .HasColumnType("longtext");

                    b.Property<string>("vehicle_year")
                        .HasColumnType("longtext");

                    b.HasKey("appointment_id");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("server.Models.Bays", b =>
                {
                    b.Property<int>("bay_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("bay_id"));

                    b.Property<string>("bay_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("bay_type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("is_Active")
                        .HasColumnType("int");

                    b.HasKey("bay_id");

                    b.ToTable("bays", (string)null);
                });

            modelBuilder.Entity("server.Models.ChecklisterLog", b =>
                {
                    b.Property<int>("checklister_logs_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("checklister_logs_id"));

                    b.Property<string>("appointment_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("postservice_end")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("postservice_start")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("postservice_status")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("preservice_end")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("preservice_start")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("preservice_status")
                        .HasColumnType("longtext");

                    b.HasKey("checklister_logs_id");

                    b.HasIndex("appointment_id")
                        .IsUnique();

                    b.ToTable("checklister_logs", (string)null);
                });

            modelBuilder.Entity("server.Models.JobconLog", b =>
                {
                    b.Property<int>("jobcon_logs_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("jobcon_logs_id"));

                    b.Property<string>("appointment_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("bay_id")
                        .HasColumnType("int");

                    b.Property<string>("checklister_status")
                        .HasColumnType("longtext");

                    b.Property<string>("parts_status")
                        .HasColumnType("longtext");

                    b.Property<string>("sa_status")
                        .HasColumnType("longtext");

                    b.Property<string>("workshop_status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("jobcon_logs_id");

                    b.ToTable("jobcon_logs");
                });

            modelBuilder.Entity("server.Models.SaLog", b =>
                {
                    b.Property<int>("sa_logs_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("sa_logs_id"));

                    b.Property<string>("appointment_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("receiving_end")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("receiving_start")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("receiving_status")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("releasing_end")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("releasing_start")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("releasing_status")
                        .HasColumnType("longtext");

                    b.HasKey("sa_logs_id");

                    b.HasIndex("appointment_id")
                        .IsUnique();

                    b.ToTable("sa_logs");
                });

            modelBuilder.Entity("server.Models.Service", b =>
                {
                    b.Property<string>("service_id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("appointment_id")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("created_by")
                        .HasColumnType("longtext");

                    b.Property<string>("current_bay_id")
                        .HasColumnType("longtext");

                    b.Property<int?>("current_duration_minutes")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("current_start_time")
                        .HasColumnType("time(6)");

                    b.Property<int?>("estimated_duration_minutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("last_modified_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("last_modified_by")
                        .HasColumnType("longtext");

                    b.Property<string>("original_bay_id")
                        .HasColumnType("longtext");

                    b.Property<TimeOnly?>("original_start_time")
                        .HasColumnType("time(6)");

                    b.Property<string>("service_type")
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .HasColumnType("longtext");

                    b.HasKey("service_id");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("server.Models.User", b =>
                {
                    b.Property<int>("users_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("users_id"));

                    b.Property<string>("assigned_bay_id")
                        .HasColumnType("longtext");

                    b.Property<string>("full_name")
                        .HasColumnType("longtext");

                    b.Property<int>("position_id")
                        .HasColumnType("int");

                    b.HasKey("users_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("server.Models.ChecklisterLog", b =>
                {
                    b.HasOne("server.Models.Appointment", "Appointment")
                        .WithOne("ChecklisterLog")
                        .HasForeignKey("server.Models.ChecklisterLog", "appointment_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("server.Models.SaLog", b =>
                {
                    b.HasOne("server.Models.Appointment", "Appointment")
                        .WithOne("SaLog")
                        .HasForeignKey("server.Models.SaLog", "appointment_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("server.Models.Appointment", b =>
                {
                    b.Navigation("ChecklisterLog");

                    b.Navigation("SaLog");
                });
#pragma warning restore 612, 618
        }
    }
}
